### ISSUE TITLE
Environment variables doesn't work

### ISSUE THREAD

**Issue by Aliaksandr-K-JazzTeam** [notify-events/jenkins#1]
In message text I can't use environment variables

**Comment by matrozov** [comment]
Hi. We released version 1.1.0 with environment variables support. It will be available for installation soon.

**Comment by Aliaksandr-K-JazzTeam** [comment]
Hi, @matrozov 
Thanks for fast response. But I saw that not all vars are working. I.e. in post-build step email notification I use vars: $PROJECT_NAME, $BUILD_STATUS, ${FILE,path="path/to/file"}, but in Notify.Events they doesn't work

**Comment by matrozov** [comment]
Hi, @Aliaksandr-Kasko-JazzTeam
Thanks for the feedback. I will additionally look at these variables. We’ll try to resolve the issue this week.

**Comment by matrozov** [comment]
Hi, @Aliaksandr-Kasko-JazzTeam

**Comment by matrozov** [comment]
@Aliaksandr-Kasko-JazzTeam 
We have released version 1.2.0 with more complete support for environment variables. I checked the variables $PROJECT_NAME and $BUILD_STATUS and they worked. Please check and confirm and I will close issue after that.

**Comment by Aliaksandr-K-JazzTeam** [comment]
Hi, @matrozov 
Yes, I confirm that all environment variables work. Even ${FILE,path="/path/to/file"}
